export const defaultBrettnames = [
  "Physique / Resist",
  "Willpower",
  "Fight",
  "Blast",
  "Strength",
  "Acrobatics / Dodge",
  "Flying",
  "Mana",
  "Craft",
  "Stealth",
  "Notice",
  "Persuasion",
  "Deception",
  "Intimidation",
  "Performance",
  "Empathy",
  "Intelligence",
  "Lore",
  "Resources",
  "Contacts",
  "Nature",
  "Medicine",
  "Agility",
];

export const defaultBrettOwlHouseCharacter = {
  name: "",
  totalPoints: 20,
  skills: defaultBrettnames,
};
